{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim.data) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 15Gi
{{- end }}
---
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim.config) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
